### PR TITLE
modified for Debian 8 Jessie + letsencrypt certbot integration

### PR DESCRIPTION
**Pull request by mdPlusPlus**
- modified for Debian 8 Jessie
- updated configuration
- removed unnecessary packages
- changed php-suhosin installation to not use dotdeb.org
- enabled OPcache
- added IPv6
- added SPDY (will be changed to HTTP/2 as soon as a fitting nginx is available in the stable repo)
- added TLS via letsencrypt (installs certbot, automates renewal, adds new certificate at virtual host creation)
- creation of (bigger) dhparam.pem

**Attention:** Some features are **not** properly tested.

### CODE REVIEW

**Comment by faultylee** [comment]
Good work on the changes. I've not been using this for a while and moving over to dockerizing my site, I'll wait for @aatishnn to approve the merge. 

Btw, the README.md might need some tweaking.

**Comment by aatishnn** [comment]
Thank you very much for the pull request. Similar to @faultylee , I wasn't maintaining this script because I was no longer using this. Until I get some time to review this, I have updated the README to point it to your repo. If you want to maintain this repo, I would be glad to add you as a collaborator.

**Comment by mdPlusPlus** [comment]
I think just pointing to my repo in your readme will do. I'm not sure how long and how frequent I will submit changes to it, though. As of now everything seems to work fine, but I still have some things on my to do list that I'd like to implement sometime.

**Comment by aatishnn** [comment]
@mdPlusPlus Sure. Do remind me of major updates so that I can update it on README.

**Pull request closed without merging**
